"""Render the Homebrew formula for jarvis standalone release archives."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

RELEASE_BASE_URL = "https://github.com/jarvis-intelligence/homebrew-jarvis/releases/download"
PLATFORMS = ("darwin_arm64", "darwin_amd64", "linux_arm64", "linux_amd64")
SEMANTIC_VERSION_RE = re.compile(r"(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)")
SHA256_RE = re.compile(r"[0-9a-f]{64}")


def _artifact_url(version: str, release_tag: str, platform: str) -> str:
    return f"{RELEASE_BASE_URL}/{release_tag}/jarvis_{version}_{platform}.tar.gz"


def _validate_release(version: str, release_tag: str) -> None:
    if SEMANTIC_VERSION_RE.fullmatch(version) is None:
        raise ValueError(f"version must be semantic X.Y.Z, got {version!r}")

    if not release_tag:
        raise ValueError("release tag must not be empty")


def _validate_checksums(checksums: dict[str, str]) -> None:
    expected = set(PLATFORMS)
    actual = set(checksums)
    missing = expected - actual
    unexpected = actual - expected
    if missing or unexpected:
        details = []
        if missing:
            details.append(f"missing: {', '.join(sorted(missing))}")
        if unexpected:
            details.append(f"unexpected: {', '.join(sorted(unexpected))}")
        raise ValueError(f"checksum platform mismatch ({'; '.join(details)})")

    for platform in PLATFORMS:
        digest = checksums[platform]
        if SHA256_RE.fullmatch(digest) is None:
            raise ValueError(
                f"invalid SHA-256 for {platform}: {digest!r}; "
                "expected 64 lowercase hexadecimal characters"
            )


def _validate_inputs(
    version: str, release_tag: str, checksums: dict[str, str]
) -> None:
    _validate_release(version, release_tag)
    _validate_checksums(checksums)


def render(version: str, release_tag: str, checksums: dict[str, str]) -> str:
    """Return the generated jarvis.rb formula as Ruby source text."""
    _validate_inputs(version, release_tag, checksums)
    urls = {
        platform: _artifact_url(version, release_tag, platform)
        for platform in PLATFORMS
    }

    return f'''# Generated by jarvis's publish-native workflow; do not edit by hand.
class Jarvis < Formula
  desc "Local-first code intelligence MCP server"
  homepage "https://github.com/jarvis-intelligence/jarvis-index"
  url "{urls["darwin_arm64"]}"
  sha256 "{checksums["darwin_arm64"]}"

  depends_on "universal-ctags"

  on_macos do
    on_arm do
      url "{urls["darwin_arm64"]}"
      sha256 "{checksums["darwin_arm64"]}"
    end
    on_intel do
      url "{urls["darwin_amd64"]}"
      sha256 "{checksums["darwin_amd64"]}"
    end
  end

  on_linux do
    on_arm do
      url "{urls["linux_arm64"]}"
      sha256 "{checksums["linux_arm64"]}"
    end
    on_intel do
      url "{urls["linux_amd64"]}"
      sha256 "{checksums["linux_amd64"]}"
    end
  end

  def install
    libexec.install Dir["libexec/*"]
    bin.install_symlink libexec/"jarvis" => "jarvis"
    bin.install_symlink libexec/"jarvis" => "jarvis-server"

    ctags = formula_opt_bin("universal-ctags")/"ctags"
    (libexec/"_internal/native-bin/universal-ctags").write <<~SH
      #!/bin/sh
      exec "#{{ctags}}" "$@"
    SH
    chmod 0755, libexec/"_internal/native-bin/universal-ctags"
  end

  test do
    assert_match version.to_s, shell_output("#{{bin}}/jarvis --version")
  end
end
'''


def _read_checksum(path: Path) -> str:
    parts = path.read_text().split()
    if not parts:
        raise ValueError(f"empty checksum file: {path}")
    return parts[0]


class _ArgumentParser(argparse.ArgumentParser):
    def error(self, message: str) -> None:
        raise ValueError(message)


def main(argv: list[str] | None = None) -> int:
    parser = _ArgumentParser(description=__doc__)
    parser.add_argument("--version", required=True)
    parser.add_argument("--release-tag", required=True)
    parser.add_argument("--checksum-dir", required=True, type=Path)
    try:
        args = parser.parse_args(argv)
        _validate_release(args.version, args.release_tag)
        checksums = {}
        for platform in PLATFORMS:
            name = f"jarvis_{args.version}_{platform}.tar.gz"
            checksum = args.checksum_dir / f"{name}.sha256"
            checksums[platform] = _read_checksum(checksum)
        formula = render(args.version, args.release_tag, checksums)
    except (OSError, ValueError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    print(formula, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
